// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package menus

import (
	"sync/atomic"
	"time"

	"github.com/three-plus-three/modules/toolbox"
)

type CachedValue struct {
	MaxAge int64
	data   atomic.Value
}

type cachedData struct {
	value     []toolbox.Menu
	timestamp int64
}

func (cv *CachedValue) Get() []toolbox.Menu {
	var v []toolbox.Menu
	return cv.Read(v, cv.MaxAge)
}

func (cv *CachedValue) GetWithDefault(v []toolbox.Menu) []toolbox.Menu {
	return cv.Read(v, cv.MaxAge)
}

func (cv *CachedValue) Read(v []toolbox.Menu, maxAge int64) []toolbox.Menu {
	o := cv.data.Load()
	if o == nil {
		return v
	}
	cdata, ok := o.(*cachedData)
	if !ok {
		return v
	}
	if (cdata.timestamp + maxAge) < time.Now().Unix() {
		return v
	}
	return cdata.value
}

func (cv *CachedValue) Set(v []toolbox.Menu, t time.Time) {
	cv.data.Store(&cachedData{
		value:     v,
		timestamp: t.Unix(),
	})
}
